replicaCount: 1

image:
  repository: ghcr.io/<your-username>/<db-image>
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 5432
  nodePort: 30082

resources: {}

# 環境変数例（Postgres）
env:
  POSTGRES_USER: user
  POSTGRES_PASSWORD: password
  POSTGRES_DB: mydb
